### ISSUE TITLE
Replace branches/find_nearest_branch()

### ISSUE THREAD

**Issue by rhutten** [Deltares/hydromt_delft3dfm#5]
**What is the need for this task.**
We are now using a copied version of the find_nearest_branch() method of D-HyDAMO. This should change.

**What is the task?**
Execute the steps bellow:

- Investigate HydroMT nearest join function --> how we could replace the overal, intersect and ends method from find_nearest_branch().
- Implement the function into plugin
- Test if it works properly and replaces D-HyDAMO function: propose generate the model with D-HyDAMO function and with updated nearest join function. Check the difference in input files. 

**Decisions**

- For the ends method, so line ends snapped to another line, like culverts, we decided that for the first release we will not adopt this method. We assume that culverts are for now points and we do not have setup culverts.

**Comment by xldeltares** [comment]
Function is complete but due to precision differences, the tests keep failing. 

Proposed solution after discussion with Hélène: 
in write geoms, write the geojson with certain percision. additional benefit: smaller size geojson. 

Reopen the issue and describe how this could have influenced test results due to precision [More efficient JSON in staticgeoms · Issue #30 · Deltares/hydromt (github.com)](https://github.com/Deltares/hydromt/issues/30)
